### ISSUE TITLE
[Suggestion] Adding a new localization

### ISSUE THREAD

**Issue by VladWinner** [RikkaApps/WADB#14]
Can you approve changes to the Russian localization for WADB, App Ops, and Shizuku?

Thank you for your hard work.

**Comment by haruue** [comment]
Yep! You can contribute to those localization files [here](https://weblate.rikka.app/).

**Comment by VladWinner** [comment]
Already done ☺

**Comment by haruue** [comment]
Thanks! RikkaW has imported your localization file in the 0eea49b2f42f82e922ba5a388105233f9cfc81f0 and it will be released in v5.0.1.
