### ISSUE TITLE
Not able to disable in the notification bar

### ISSUE THREAD

**Issue by Thewisem** [RikkaApps/WADB#16]
The diaable button doesn't work in the notification bar. When I pressed it, it didn't disable the wireless adb. Plus even whenI disable on the app and close it, the notification is still there

**Comment by haruue** [comment]
Thank you for reporting this issue. For us to further investigate this issue, please provide the following additional information:
+ The manufacturer and model of your device. (e.g. Xiaomi 10 Pro)
+ The Android version and customized ROM version you are using. (e.g. Android 11, MIUI 12.5)

**Comment by haruue** [comment]
In addition, please provide a screenshot of the WADB notification you tried to interact with. A screen recording video would be better if acceptable.

**Comment by Thewisem** [comment]
Device: Samsung Galaxy Tab A SM P555
Android Version:7.1.1 Nougat

**Comment by Thewisem** [comment]
https://user-images.githubusercontent.com/74511929/122462356-2adfa300-cfbd-11eb-8077-4869b3ab799c.mp4

**Comment by Thewisem** [comment]
Here. :)

**Comment by haruue** [comment]
It seems like the WADB cannot obtain the root permission on your device while running in the background. 
Which root manager are you using? (e.g. Magisk)

**Comment by Thewisem** [comment]
None

**Comment by Thewisem** [comment]
Uhhh is there a way for you to do it without root or should I always have to force stop for it to finally stop?

**Comment by haruue** [comment]
> Uhhh is there a way for you to do it without root or should I always have to force stop for it to finally stop?

Nope, WADB won't function properly without root. **root is a must**.
