### ISSUE TITLE
Quick settings tile wrong behaviour

### ISSUE THREAD

**Issue by mgood7123** [RikkaApps/WADB#19]
In Samsung, tapping on the quick settings tile CAN, but not ALWAYS, invoke the `next song` media action

**Comment by RikkaW** [comment]
This is out of our control.

**Comment by mgood7123** [comment]
> This is out of our control.

How so?

**Comment by RikkaW** [comment]
SystemUI controls this :)

**Comment by mgood7123** [comment]
System ui controls what happens when the tile is clicked?

**Comment by RikkaW** [comment]
SystemUI controls what app is used when clicking the tile

**Comment by haruue** [comment]
I saw you are maintaining lots of projects, so it should be OK to talk about this issue in detail.

Android, as a modern operating system, has many features that are not implemented by applications. Instead, the Android OS provides a series of methods, which is called the "[API][1]". Applications use these APIs to tell OS what they want to do, and the OS determines the detailed implementation.

In this example, the OS provides an API named [TileService][2] for those applications who want to display a tile. This API has a series of callback methods, which will be called when users interact with the quick settings tiles. For example, when the user clicks the tile, the [TileService#onClick()][3] will be called. We just extend this class in the WADB, implemented those callbacks, which you can find in the [WadbTileService][4]. However, what this API really does is implemented by the system. As you can see, the only thing we know is we did nothing about media action in this service. There is nothing we can do to fix this bug.

So what would be the reason for this problem? I think there are two possibilities.
1. There is a bug in Samsung's customized system. You can update your system to the latest version. If this problem still persists, you can try to find other people who also use devices of the same model, if they also encountered a similar problem, please report this bug to Samsung.
2. If you are using Xposed, please note that an Xposed module can modify the implements of Android frameworks. So maybe there is a malfunction on your device which causes this problem. Please try to disable those Xposed modules one by one to check which module is the cause. And report this bug to the maintainer of that module.

[1]: https://en.wikipedia.org/wiki/API
[2]: https://developer.android.com/reference/android/service/quicksettings/TileService
[3]: https://developer.android.com/reference/android/service/quicksettings/TileService#onClick()
[4]: https://github.com/RikkaApps/WADB/blob/d4a007c6f60f830628cc2228a0cec0184abb27e6/app/src/main/java/moe/haruue/wadb/service/WadbTileService.java

**Comment by mgood7123** [comment]
> SystemUI controls what app is used when clicking the tile

Hmmm

**Comment by mgood7123** [comment]
> I saw you are maintaining lots of projects, so it should be OK to talk about this issue in detail.
> 
> Android, as a modern operating system, has many features that are not implemented by applications. Instead, the Android OS provides a series of methods, which is called the "[API][1]". Applications use these APIs to tell OS what they want to do, and the OS determines the detailed implementation.
> 
> In this example, the OS provides an API named [TileService][2] for applications that want to display a tile. This API has a series of callback methods, which will be called when users interact with the quick settings tiles. For example, when the user clicks the tile, the [TileService#onClick()][3] will be called. We just extended this class in the WADB, and implemented those callbacks, which you can find in the [WadbTileService][4]. However, what this API really does is implemented by the system. As you can see, the only thing we know is we did nothing about media action in this service. There is nothing we can do to fix this bug.
> 
> So what would be the reason for this problem? I think there are two possibilities.
> 1. There is a bug in Samsung's customized system. You can update your system to the latest version. If this problem still persists, you can try to find other people who also use devices of the same model, if they also encountered a similar problem, please report this bug to Samsung.
> 2. If you are using Xposed, please note that an Xposed module can modify the implementation of Android frameworks. So maybe there is a malfunction on your device which causes this problem. Please try to disable those Xposed modules one by one to check which module is the cause. And report this bug to the maintainer of that module.
> 
> [1]: https://en.wikipedia.org/wiki/API
> [2]: https://developer.android.com/reference/android/service/quicksettings/TileService
> [3]: https://developer.android.com/reference/android/service/quicksettings/TileService#onClick()
> [4]: https://github.com/RikkaApps/WADB/blob/d4a007c6f60f830628cc2228a0cec0184abb27e6/app/src/main/java/moe/haruue/wadb/service/WadbTileService.java

hmm ok

**Comment by mgood7123** [comment]
> I saw you are maintaining lots of projects, so it should be OK to talk about this issue in detail.
> 
> Android, as a modern operating system, has many features that are not implemented by applications. Instead, the Android OS provides a series of methods, which is called the "[API][1]". Applications use these APIs to tell OS what they want to do, and the OS determines the detailed implementation.
> 
> In this example, the OS provides an API named [TileService][2] for applications that want to display a tile. This API has a series of callback methods, which will be called when users interact with the quick settings tiles. For example, when the user clicks the tile, the [TileService#onClick()][3] will be called. We just extended this class in the WADB, and implemented those callbacks, which you can find in the [WadbTileService][4]. However, what this API really does is implemented by the system. As you can see, the only thing we know is we did nothing about media action in this service. There is nothing we can do to fix this bug.
> 
> So what would be the reason for this problem? I think there are two possibilities.
> 1. There is a bug in Samsung's customized system. You can update your system to the latest version. If this problem still persists, you can try to find other people who also use devices of the same model, if they also encountered a similar problem, please report this bug to Samsung.
> 2. If you are using Xposed, please note that an Xposed module can modify the implementation of Android frameworks. So maybe there is a malfunction on your device which causes this problem. Please try to disable those Xposed modules one by one to check which module is the cause. And report this bug to the maintainer of that module.
> 
> [1]: https://en.wikipedia.org/wiki/API
> [2]: https://developer.android.com/reference/android/service/quicksettings/TileService
> [3]: https://developer.android.com/reference/android/service/quicksettings/TileService#onClick()
> [4]: https://github.com/RikkaApps/WADB/blob/d4a007c6f60f830628cc2228a0cec0184abb27e6/app/src/main/java/moe/haruue/wadb/service/WadbTileService.java

This is probably a rare bug then
