### ISSUE TITLE
Support hotspot connection

### ISSUE THREAD

**Issue by BryanGIG** [RikkaApps/WADB#20]

**Comment by haruue** [comment]
I think it should be able to connect ADB via the hotspot of the device itself. In fact, I did this every day when I was still in the university.
The only problem is how to obtain the hotspot device's IP address, which was always `192.168.43.1` in the good old days and randomized and not even being displayed in the system settings now. You can install the [Termux](https://github.com/termux/termux-app), run `ip -o -4 addr | grep wlan` in it and you will be able to find it out.

**Comment by BryanGIG** [comment]
Well I try your method and it's not working. There's no result in it.

When I enable adb wireless with WADB, the ip address is 0.0.0.0 and it failed.
But then I see in settings phone and I got my ip address then I try to connect it and it's working.

![IMG_20210817_182218](https://user-images.githubusercontent.com/60846364/129717662-67a451c0-4a50-4249-8e7c-d5c65430c015.jpg)
