### ISSUE TITLE
Working with adb instead of just root

### ISSUE THREAD

**Issue by iagocity** [RikkaApps/WADB#26]
Would be great if users without root could use the app giving the app android.permission_WRITE_SECURE_SETTINGS with adb. However, if I try to do it, it tells me the app didn't request this permission.

**adb shell pm grant moe.haruue.wadb android.permission.WRITE_SECURE_SETTINGS**

**Comment by haruue** [comment]
I don't think WADB would work with WRITE_SECURE_SETTINGS.

If you think it is possible, just implement it and send a pull request to us, thx.

**Comment by hlfei-2009** [comment]
> 如果无需root权限的用户也能通过adb命令授予应用android.permission_WRITE_SECURE_SETTINGS权限，那就太好了。但是，当我尝试这样做时，系统提示应用没有请求此权限。
> 
> **adb shell pm grant moe.haruue.wadb android.permission.WRITE_SECURE_SETTINGS**

是因为在此应用的 AndroidManifest.xml 中没有声明<uses-permission android.permission_WRITE_SECURE_SETTINGS />这个权限。
