### ISSUE TITLE
100% FC at start in version 6.0.0 on android 6.0.1

### ISSUE THREAD

**Issue by NotesOfReality** [RikkaApps/WADB#27]
The latest version of this app unfortunately forcedly closes as I try to open/launch it on an Android 6.0.1 (`armeabi-v7a` ABI, 32-bit mode, "MX Q PRO II/4K") device,  it's therefore completely unusable , such an issue never occurs with the 5.1.1 version of this app.

Hopefully [this logcat](https://katb.in/omusabivoxa) allows you to fix this issue if you'd like to.
Unfortunately I'm totally clueless as to why it happens, and (obviously?) I've already cleared the app data and/or cache and uninstalled and reinstalled it without getting any different outcome.
If it could be helpful I'd be willing to run basically any command on this device.

**Comment by NotesOfReality** [comment]
Sorry for the lacking logcat, if you'd still like to help me hopefully [this one](https://katb.in/rirasuxoyoz) isn't, here's a [compr. archive with `dmesg` output and device info](https://mega.nz/file/pwkjUSCR#OC7N8V9DTs-n89G9tYNNcIzg5qwmZOKdJjZSFOn6Ks0) just in case a logcat isn't enough.

I've used [App Manager](https://github.com/MuntashirAkon/AppManager)'s "Log Viewer" with the verbose log level, and I had enabled the "Omit sensitive info" so now that I disabled it the output logcat might be more effectively informative 🤔 .

**Comment by haruue** [comment]
You logcat is still incompleted.

```
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.View.layout(View.java:16641)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.View.layout(View.java:16641)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.View.layout(View.java:16641)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.View.layout(View.java:16641)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.View.layout(View.java:16641)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.View.layout(View.java:16641)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
06-03 12:34:42.777 E/AndroidRuntime( 7601): 	at android
06-03 12:34:45.236 I/Process ( 7601): Sending signal. PID: 7601 SIG: 9
06-03 12:34:45.323 I/ActivityManager( 4101): Process moe.haruue.wadb (pid 7601) has died
```

Please note the `Process moe.haruue.wadb (pid 7601) has died` in you log. I'd recommend you capture the full log with `adb logcat -v threadtime '*:V'`, find such a line `Process moe.haruue.wadb (pid ####) has died` , and filter the log with the pid (would changes every time) in it.

Then there will not be many lines of log, and you can check lines one by one to remove any "sensitive info" if you want.

**Comment by NotesOfReality** [comment]
First of all, I tested [wadb-v6.0.0.r204.212af1d-release.apk.zip](https://github.com/RikkaApps/WADB/files/8831362/wadb-v6.0.0.r204.212af1d-release.apk.zip) ([from #28](https://github.com/RikkaApps/WADB/issues/28#issuecomment-1145785942)) and, surprisingly enough, it works _flawlessly without any issue_, **wow**.

[Here](https://katb.in/defejubefad)'s a hopefully useful filtered logcat nonetheless, with the FC at launch of [v.6.0.0](https://github.com/RikkaApps/WADB/releases/tag/v6.0.0).
[Here](https://katb.in/axepatibada) instead is another logcat, with the installation and short testing of [wadb-v6.0.0.r204.212af1d-release.apk.zip](https://github.com/RikkaApps/WADB/files/8831362/wadb-v6.0.0.r204.212af1d-release.apk.zip), just in case.
