### ISSUE TITLE
`eth0` net. interface IP is not displayed in the home fragment

### ISSUE THREAD

**Issue by NotesOfReality** [RikkaApps/WADB#28]
If an android device is connected by an ethernet adapter (recognized as `eth0` in my case) the whole app works perfectly _fine_, that is you can flawlessly toggle the "Wireless ADB" on/off as you please and it all works well.
This behaviour can be observed on the versions 6.0.0 and 5.1.1 of this app, I haven't tested the previous ones.

[Here's a logcat](https://katb.in/ehuhodesede) which has run since I've plugged the ethernet adapter until I've toggled "Wireless ADB" by the app itself, run a test command over adb by my pc and toggled it off, I don't know if it could be really useful but I guess it can't hurt.
Here's an eventually(?) useful `ip` output:
```
vayu:/ $ ip -o -4 addr | grep eth
70: eth0    inet 192.168.1.130/24 brd 192.168.1.255 scope global eth0\       valid_lft forever preferred_lft forever
```

It unfortunately just doesn't display the correct IP address in the home fragment, it displays "0.0.0.0:5555" instead.
![Screenshot_20220602_222853](https://user-images.githubusercontent.com/11523796/171733161-27796254-a6bc-459f-a129-dba0d328cd92.jpg)

**Comment by haruue** [comment]
Oh, that's because we only retrieve IP addresses from wlan0/wlan1, not eth0.

https://github.com/RikkaApps/WADB/blob/c6fe49938efa35487a075c07b6bf7d63d847799d/app/src/main/java/moe/haruue/wadb/util/NetworksUtils.java#L31-L40

~~And WADB is "Wireless adb" instead of "Wired adb",~~ whatever.

So maybe we should provide an option to lets you select a customized interface, or just retrieve IP from every interface and display them in the format `"[$interface] $address"`.

**Comment by NotesOfReality** [comment]
> ~And WADB is "Wireless adb" instead of "Wired adb",~ whatever.

Thanks for considering this issue eventhough of it! ❤️ 


_If I may,_ I'd suggest you to keep the "WiFi" and "AP" UI strings respectively for `wlan0` and `wlan1` net. interf. and display the other interfaces in the format `"[$interface] $address"`.

Just in case you choose to implement a net. inter. selector menu, [Sharik's one](https://github.com/marchellodev/sharik/commit/8aed3b090b798855624c546ade5234cf4e140001) _could_ be worth having a peek at imho (disclaimer: I'm just a power user).

**Comment by haruue** [comment]
Could you please try commit 212af1d68ec6dcc3ba2b93e37a966a3692a40d2a, `ethX` should be showed in IP lists now.
[wadb-v6.0.0.r204.212af1d-release.apk.zip](https://github.com/RikkaApps/WADB/files/8831362/wadb-v6.0.0.r204.212af1d-release.apk.zip)

**Comment by NotesOfReality** [comment]
It does and the app works perfectly so far! Thanks! ❤️

**Comment by NotesOfReality** [comment]
As of https://github.com/RikkaApps/WADB/commit/212af1d68ec6dcc3ba2b93e37a966a3692a40d2a as [these screenshot](https://mega.nz/folder/dtVwDRgR#NwuVjocOzTLvItiyryI26g) show I'd say it works perfectly too.
